//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Process
    {
        public int Study_Payment_Id { get; set; }
        public Nullable<double> Study_Amount { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<bool> Study_IsPaid { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Comment { get; set; }
        public string Currency { get; set; }
        public string PaymentType { get; set; }
        public string Result_Code { get; set; }
        public string Result_Description { get; set; }
        public string Result_BuildNumber { get; set; }
        public string Result_Timestamp { get; set; }
        public string Result_Ndc { get; set; }
        public string Result_Id { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<int> Payment_Type { get; set; }
    
        public virtual Payment_Type Payment_Type1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
