//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicSubmission
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REU_RegistrationEntities : DbContext
    {
        public REU_RegistrationEntities()
            : base("name=REU_RegistrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collage> Collages { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Group_Status> Group_Status { get; set; }
        public virtual DbSet<LanguageMaster> LanguageMasters { get; set; }
        public virtual DbSet<Lanuage_Detials> Lanuage_Detials { get; set; }
        public virtual DbSet<LastUpdate> LastUpdates { get; set; }
        public virtual DbSet<Log_File> Log_File { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<Notification_Employee> Notification_Employee { get; set; }
        public virtual DbSet<Notification_Master> Notification_Master { get; set; }
        public virtual DbSet<Notification_Show> Notification_Show { get; set; }
        public virtual DbSet<Payment_Process> Payment_Process { get; set; }
        public virtual DbSet<Payment_Type> Payment_Type { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Permission_Group> Permission_Group { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<Rosom_Request> Rosom_Request { get; set; }
        public virtual DbSet<Rosom_Response> Rosom_Response { get; set; }
        public virtual DbSet<Sequence> Sequences { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Concat> Student_Concat { get; set; }
    }
}
