//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Student_Id { get; set; }
        public string Student_SSN { get; set; }
        public string Student_Name { get; set; }
        public string Student_Phone { get; set; }
        public string Student_Email { get; set; }
        public string Student_High_School_Degree { get; set; }
        public string Student_Capabilities_Degree { get; set; }
        public string Student_My_Achievement_Degree { get; set; }
        public Nullable<System.DateTime> Student_CreationDate { get; set; }
        public Nullable<int> Student_Employee_Id { get; set; }
        public Nullable<System.DateTime> Student_Assign_Date { get; set; }
        public Nullable<int> Student_Image_Profile_Id { get; set; }
        public Nullable<int> Student_Specialization_Id { get; set; }
        public Nullable<int> Student_Nationality_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual File File { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
